name: Auth
 
on:
  push:
    branches: [latest, testing]
    paths: [auth/**]
    tags: [ v* ]
 
env:
  # Use docker.io for Docker Hub (Default) / Use ghcr.io for GitHub Container Registry
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
 
jobs:
  docker:
    # Will run on latest and testing only
    if: (github.ref_name == 'latest' || github.ref_name == 'testing') && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Make ENVFILE (LATEST)
        if: github.ref_name == 'latest'
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_COOKIE_SECRET: ${{ secrets.PROD_JWT_SECRET_KEY }}
          envkey_PUBKEY: ${{ secrets.PROD_PUBKEY }}
          file_name: .env
          directory: ./auth/
      -
        name: Make ENVFILE (TESTING)
        if: github.ref_name == 'testing'
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_COOKIE_SECRET: ${{ secrets.TEST_JWT_SECRET_KEY }}
          envkey_PUBKEY: ${{ secrets.TEST_PUBKEY }}
          file_name: .env
          directory: ./auth/
      -
        name: create-json (LATEST)
        if: github.ref_name == 'latest'
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "client_secrets.json"
          json: ${{ secrets.PROD_CLIENT_SECRETS }}
          dir: 'auth/'
      -
        name: create-json (TESTING)
        if: github.ref_name == 'testing'
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "client_secrets.json"
          json: ${{ secrets.TEST_CLIENT_SECRETS }}
          dir: 'auth/'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=auth-,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      -
        name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # Username and Password for DOCKER HUB
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Username and Password for GITHUB CONTAINER REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: "./auth"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
